image: docker:latest

variables:
  # When using dind service, we need to instruct docker to talk with
  # the daemon started inside of the service. The daemon is available
  # with a network connection instead of the default
  # /var/run/docker.sock socket.
  # port 2375 for no TLS connection (insecure)
  # port 2376 for TLS connection
  DOCKER_HOST: tcp://docker:2376

  # Specify to Docker where to create the certificates, Docker will
  # create them automatically on boot, and will create
  # `/certs/client` that will be shared between the service and job
  # container, thanks to volume mount from config.toml
  DOCKER_TLS_CERTDIR: "/certs"
  
  # These are usually specified by the entrypoint, however the
  # Kubernetes executor doesn't run entrypoints
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4125
  DOCKER_TLS_VERIFY: 1
  DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"

  # These are for buildx
  DOCKER_DRIVER: overlay2
  DOCKER_BUILDKIT: 1
  DOCKER_CLI_EXPERIMENTAL: enabled
  BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64
  BUILDX_BUILDER: buildx
  # Name/Location of the file containing any build-args to add
  # If this file doesn't exist, then we don't build the image
  # with any build-args
  BUILD_ARG_FILE: Docker.build.args

  # By default we expect that both build/build-arm64 jobs would have executed
  # so we enable pushing both amd64/arm64 images
  PUSH_AMD64_ENABLED: "true"
  PUSH_ARM64_ENABLED: "true"

services:
  - name: docker:dind
    command: ["--experimental"]

.build_setup:
  # This is used by other jobs
  script:
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27384#note_497228752
    - |
      for i in $(seq 1 30)
      do
          docker info && break
          echo "Waiting for docker to start"
          sleep 1s
      done
    - mkdir -p $HOME/.docker
    - mkdir -p $HOME/.docker/cli-plugins/
    - wget -O $HOME/.docker/cli-plugins/docker-buildx $BUILDX_URL
    - chmod a+x $HOME/.docker/cli-plugins/docker-buildx
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker context create pipeline-builder
    - docker buildx create pipeline-builder --use --driver docker-container --name ${BUILDX_BUILDER}
    - docker buildx inspect --bootstrap ${BUILDX_BUILDER}
    - docker version
    - docker buildx
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

.build:
  stage: build
  script:
    # Builds an linux/amd64 version of the image, the Dockerfile must be platform
    # independent i.e. you can't use platform specific packages or pass through
    # variables to handle this
    - !reference [.build_setup, script]
    - |
      echo "[INFO] Identifiying the build args/image.."
      if [ -f "$BUILD_ARG_FILE" ];
      then
        BUILD_ARGS=$(cat $BUILD_ARG_FILE | sed 's/^/--build-arg /g' | paste -s -d " ")
        BUILD_CMD="--tag ${BUILD_IMAGE}-amd64 ${BUILD_ARGS}"
        
      else
        BUILD_CMD="-t ${BUILD_IMAGE}-amd64"
      fi
    - echo "[INFO] Building ${BUILD_IMAGE}-amd64"
    - docker buildx build --push --platform linux/amd64 ${BUILD_CMD} .

.build-arm64:
  stage: build
  script:
    # Builds an linux/arm64 version of the image, the Dockerfile must be platform
    # independent i.e. you can't use platform specific packages or pass through
    # variables to handle this
    - !reference [.build_setup, script]
    - |
      echo "[INFO] Identifiying the build args/image.."
      if [ -f "$BUILD_ARG_FILE" ];
      then
        BUILD_ARGS=$(cat $BUILD_ARG_FILE | sed 's/^/--build-arg /g' | paste -s -d " ")
        BUILD_CMD="--tag ${BUILD_IMAGE}-arm64 ${BUILD_ARGS}"
        
      else
        BUILD_CMD="-t ${BUILD_IMAGE}-arm64"
      fi
    - echo "[INFO] Building ${BUILD_IMAGE}-arm64"
    - docker buildx build --push --platform linux/arm64 ${BUILD_CMD} .

.push:
  stage: push
  variables:
    PUSH_IMAGE: "$EXTERNAL_REGISTRY_URL:$BUILD_TAG"
  script:
    # Pushes the BUILD_IMAGE to the location specified in the EXTERNAL_REGISTRY_URL
    # by default will attempt to push both amd64/arm64 versions of the image but this
    # can be controlled by setting the PUSH_AMD64_ENABLED/PUSH_AMD64_ENABLED variables
    # to empty in the parent job.
    - !reference [.build_setup, script]
    - echo "[INFO] Pushing image ${PUSH_IMAGE}"
    - |
      if [ -n "$PUSH_AMD64_ENABLED" ] && [ -z "$PUSH_ARM64_ENABLED" ];
      then
        # AMD64
        docker pull ${BUILD_IMAGE}-amd64
        docker tag ${BUILD_IMAGE}-amd64 ${PUSH_IMAGE}-amd64
        docker push ${PUSH_IMAGE}-amd64
        echo "[INFO] Pushed ${PUSH_IMAGE}-amd64"
      elif [ -n "${PUSH_ARM64_ENABLED}" ] && [ -z "${PUSH_AMD64_ENABLED}" ];
      then
        # ARM64
        docker pull ${BUILD_IMAGE}-arm64
        docker tag ${BUILD_IMAGE}-arm64 ${PUSH_IMAGE}-arm64
        docker push ${PUSH_IMAGE}-arm64
        echo "[INFO] Pushed ${PUSH_IMAGE}-arm64"
      elif [ -n "${PUSH_AMD64_ENABLED}" ] && [ -n "${PUSH_ARM64_ENABLED}" ];
      then
        # AMD64/ARM64
        docker pull ${BUILD_IMAGE}-amd64
        docker tag ${BUILD_IMAGE}-amd64 ${PUSH_IMAGE}-amd64
        docker push ${PUSH_IMAGE}-amd64
        echo "[INFO] Pushed ${PUSH_IMAGE}-amd64"
        echo -e
        docker pull ${BUILD_IMAGE}-arm64
        docker tag ${BUILD_IMAGE}-arm64 ${PUSH_IMAGE}-arm64
        docker push ${PUSH_IMAGE}-arm64
        echo "[INFO] Pushed ${PUSH_IMAGE}-arm64"
        echo -e
        echo "[INFO] Building manifiest ${PUSH_IMAGE} using images ${PUSH_IMAGE}-amd64 ${PUSH_IMAGE}-arm64"
        docker manifest create ${PUSH_IMAGE} ${PUSH_IMAGE}-amd64 ${PUSH_IMAGE}-arm64
        docker manifest push ${PUSH_IMAGE}
        echo "[INFO] Pushed ${PUSH_IMAGE}"
      else
        echo "[ERROR] PUSH_AMD64_ENABLED or PUSH_ARM64_ENABLED not set, unable to publish.."
        exit 1
      fi
