.vulnerability_scanning:
  image:
    name: docker.io/aquasec/trivy:latest
  stage: scan
  allow_failure: true
  interruptible: true
  variables:
    GIT_STRATEGY: none
    TRIVY_DEBUG: "false"
    TRIVY_SEVERITY: "HIGH,CRITICAL"
    TRIVY_VULN_TYPE: "os,library"
    TRIVY_TIMEOUT: "5m"
  timeout: 5m
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  when: on_success
  before_script:
    - apk update && apk add --no-cache docker-cli curl
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - curl -so junit.tpl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/junit.tpl
  script:
    - image --format template --template "@junit.tpl" -o gl-container-scanning-report.xml ${IMAGE}
  artifacts:
    reports:
      junit: gl-container-scanning-report.xml
    expire_in: 1 day
